trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: MavenAuthenticate@0
      inputs:
        mavenServiceConnections: 'maven-artifacts'
      displayName: 'Authenticate with Maven'
    - task: CmdLine@2
      displayName: 'Download JAR file from JFrog Artifactory'
      inputs:
        script: |
          mkdir -p $(Agent.TempDirectory)/jars
          curl -u admin:Reh@9968 -o $(Agent.TempDirectory)/jars/my-artifact.jar http://74.235.136.21:8081/artifactory/libs-snapshot-local/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar
    - task: PublishBuildArtifacts@1
      displayName: 'Publish JFrog Artifacts'
      inputs:
        PathtoPublish: '$(Agent.TempDirectory)/jars'
        ArtifactName: 'JFrog Artifacts'
        publishLocation: 'Container'
    - task: CmdLine@2
      displayName: 'Publish JFrog artifacts to Azure DevOps Artifacts'
      inputs:
        script: 'mvn deploy'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

